apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::$AWS_ACCOUNT_ID:role/service-role/codebuild-Iteamoa-MainPage-Build-service-role
      username: mainpage-role
      groups:
        - system:masters
