apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::<ACCOUNT_ID>:role/codebuild-Iteamoa-MainPage-Build-service-role 
      groups:
        - system:bootstrappers
        - system:nodes
  mapUsers: |
    - userarn: arn:aws:iam::<ACCOUNT_ID>:user/DevOps
      username: devops-user
      groups:
        - system:masters
