apiVersion: apps/v1
kind: Deployment
metadata:
  name: mainpage-service-deployment
  namespace: mainpage-namespace 
  labels:
    svc: mainpage
spec:
  replicas: 1  # Two pods running the service
  selector:
    matchLabels:
      svc: mainpage
  template:
    metadata:
      labels:
        svc: mainpage
    spec:
      imagePullSecrets: 
        - name: ecr-registry-secret
      containers:
       - name: main-service
         image: 970547342771.dkr.ecr.ap-northeast-2.amazonaws.com/iteamoa/mainpage:latest # Use ECR
         ports:
          - containerPort: 8080  # Check container's exposed port 
