apiVersion: v1
kind: Service
metadata:
  name: mainpage-service
  namespace: default #mainpage-namespace
spec:
  selector:
    node: local #fargate
  ports:
    - protocol: TCP
      port: 8080             # Public-facing port/Service port
      targetPort: 8080       # Container port
  type: NodePort            # Exposes the service