apiVersion: v1
kind: Service
metadata:
  name: mainpage-service
  namespace: iteamoa-mainpage-namespace
spec:
  selector:
    node: fargate
  ports:
    - protocol: TCP
      port: 8080             # Public-facing port/Service port
      targetPort: 8080       # Container port
  type: ClusterIP             # Exposes the service