apiVersion: v1
kind: Service
metadata:
  name: mainpage-service
  namespace: mainpage-namespace
spec:
  selector:
    node: local #fargate
  ports:
    - protocol: TCP
      port: 80             # Public-facing port/Service port
      targetPort: 8080       # Container port
  type: LoadBalancer            # Exposes the service