apiVersion: apps/v1
kind: Deployment
metadata:
  name: mainpage-service-deployment
  namespace: main-namespace  # Match the Fargate namespace
  labels:
    app: fargate
spec:
  replicas: 1  # Two pods running the service
  selector:
    matchLabels:
      app: fargate
  template:
    metadata:
      labels:
        app: fargate
    spec:
      serviceAccountName: login-service-sa
      containers:
      - name: main-service
        image: ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/iteamoa/mainpage:latest # Use ECR
        ports:
        - containerPort: 8080  # Check container's exposed port 
