apiVersion: apps/v1
kind: Deployment
metadata:
  name: mainpage-service-deployment
  namespace: mainpage-namespace  # Match the Fargate namespace
  labels:
    app: fargate
spec:
  replicas: 1  # Two pods running the service
  selector:
    matchLabels:
      app: fargate
  template:
    metadata:
      labels:
        app: fargate
    spec:
      containers:
      - name: mainpage-service
        image: <AWS_ACCOUNT_ID>.dkr.ecr.<AWS_DEFAULT_REGION>.amazonaws.com/iteamoa/mainpage:latest # Use ECR
        imagePullPolicy: Never
        ports:
        - containerPort: 8080  # Check container's exposed port 
