apiVersion: apps/v1
kind: Deployment
metadata:
  name: mainpage-service-deployment
  namespace: main-namespace  # Match the Fargate namespace
  labels:
    app: fargate
    svc: main
spec:
  replicas: 1  # Two pods running the service
  selector:
    matchLabels:
      app: fargate
      svc: main
  template:
    metadata:
      labels:
        app: fargate
        svc: main
    spec:
      containers:
      - name: main-service
        image: 970547342771.dkr.ecr.ap-northeast-2.amazonaws.com/iteamoa/mainpage:latest # Use ECR
        ports:
        - containerPort: 8080  # Check container's exposed port 
