# secret-aws.yaml

apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
data:
  AWS_ACCOUNT_ID: 970547342771        # echo -n "your-aws-account-id" | base64
  AWS_DEFAULT_REGION: ap-northeast-2  # 